### ISSUE TITLE
can not use function getReact on some components 

### ISSUE THREAD

**Issue by mario8x** [DevExpress/testcafe-react-selectors#15]
I tried to use the component to get props of some react component in the site: http://demo.keystonejs.com/keystone/signin , but it is always return null on some react components: SigninView, AlertView, Brand, LoginForm.
Please take a look at my script as below:

```
import ReactSelector from 'testcafe-react-selectors';

fixture `Todo App test`
	.page `http://demo.keystonejs.com/keystone/signin`;

test('[demo]: login failed', async t => {
  const allProps = await ReactSelector('SigninView').getReact(({props}) => {
    let string
    Object.keys(props).forEach((key) => {
      string = string + `${key} --`;
    })
    return string;
  })
  console.log(allProps);

  const allProps1 = await ReactSelector('AlertView').getReact(({props}) => {
    let string
    Object.keys(props).forEach((key) => {
      string = string + `${key} --`;
    })
    return string;
  })
  console.log(allProps1);

  const allProps2 = await ReactSelector('Brand').getReact(({props}) => {
    let string
    Object.keys(props).forEach((key) => {
      string = string + `${key} --`;
    })
    return string;
  })
  console.log(allProps2);

  const allProps3 = await ReactSelector('LoginForm').getReact(({props}) => {
    let string
    Object.keys(props).forEach((key) => {
      string = string + `${key} --`;
    })
    return string;
  })
  console.log(allProps3);

  const allProps4 = await ReactSelector('Form').getReact(({props}) => {
    let string
    Object.keys(props).forEach((key) => {
      string = string + `${key} --`;
    })
    return string;
  })
  console.log(allProps4);

  const allProps5 = await ReactSelector('FormField').getReact(({props}) => {
    let string
    Object.keys(props).forEach((key) => {
      string = string + `${key} --`;
    })
    return string;
  })
  console.log(allProps5);

  const allProps6 = await ReactSelector('Button').getReact(({props}) => {
    let string
    Object.keys(props).forEach((key) => {
      string = string + `${key} --`;
    })
    return string;
  })
  console.log(allProps6);

})

```

**Comment by AlexanderMoskovkin** [comment]
Hi @mario8x,

We need some time to investigate it. It possible it's the same as https://github.com/DevExpress/testcafe-react-selectors/issues/11, but it should be checked

**Comment by kirovboris** [comment]
Hi @mario8x,
We've reproduced this issue and currently working on it.

**Comment by mario8x** [comment]
Hi @kirovboris , 

Thanks for your support. I just wonder the root cause of this issue.

**Comment by kirovboris** [comment]
I've just published the new version - `testcafe-react-selectors@0.0.4`. Could you please check it?

**Comment by mario8x** [comment]
@kirovboris , 
Currently, it's still don't see a react component : `AlertView`. 
Others work well.

**Comment by kirovboris** [comment]
@mario8x, 
I can't reproduce this problem.
Could you please specify the browser and operating system?

**Comment by mario8x** [comment]
@kirovboris ,
I run on chrome browser and windows 10.

yarn testcafe -- chrome "examples/test-demo.js" --selector-timeout 15000

My test as below:
1. demo-page.js:


```
import ReactSelector from 'testcafe-react-selectors';

export default class DemoPage {
    constructor () {
        this.page = 'http://demo.keystonejs.com/keystone/signin'
        this.form = ReactSelector('LoginForm');
        this.userName = ReactSelector('FormInput').withAttribute('name','email');
        this.password = ReactSelector('FormInput').withAttribute('name','password');
        this.signin = ReactSelector('Button');
        this.alertView = ReactSelector('SigninView div AlertView');
        this.alert = ReactSelector('SigninView div AlertView Alert');
    }
}
```

2. test-demo.js


```
import Page from './demo-page.js';
import ReactSelector from 'testcafe-react-selectors';
import { Selector } from 'testcafe';

fixture `Todo App test`
	.page `http://demo.keystonejs.com/keystone/signin`;

const page = new Page();

test('[demo]: login failed', async t => {
  await t
    .typeText(page.userName,'mario8x')
    .typeText(page.password,'abc123')
    .pressKey('enter')
    .click(page.signin)

	const allProps1 = await ReactSelector('AlertView').getReact(({props}) => {
		let string
		Object.keys(props).forEach((key) => {
			string = string + `${key} --`;
		})
		return string;
	})
	console.log('AlertView ' + allProps1);

	//const message = await ReactSelector('Alert div').innerText;
	const allProps7 = await ReactSelector('Alert').getReact(({props}) => {
		let string
		Object.keys(props).forEach((key) => {
			string = string + `${key} --`;
		})
		return string;
	})
	console.log('Alert ' + allProps7);

})
```
3. The result as below:
```
 Running tests in:
 - Chrome 58.0.3029 / Windows 10 0.0.0

 Todo App test
AlertView null
Alert null
 √ [demo]: login failed
```

**Comment by kirovboris** [comment]
Thank you mario8x, i've reproduced this behavior and working on a fix. It seems `testcafe-react-selectors` can't get `props` and `state`, if several reactjs components have the common DOM element.

**Comment by mario8x** [comment]
Tks @kirovboris , 
I wonder that could we integrate **enzyme** (http://airbnb.io/enzyme/docs/api/ReactWrapper/find.html) to our modules?
 It has lot of useful methods to interact with react components.

**Comment by kirovboris** [comment]
As far as I know, `enzyme` creates a new instance of the reactjs component and requires getting a path to the component in your code. On the other hand, it doesn't work with the existing rendered component tree. `testcafe` just looks for rendered components in DOM and works with your reactjs application as with black box testing.

**Comment by kirovboris** [comment]
Published the new version - testcafe-react-selectors@0.0.5.

**Comment by mario8x** [comment]
Thanks @kirovboris , 

the latest version - testcafe-react-selectors@0.0.5 works well. 
This issue was fixed.

**Comment by kirovboris** [comment]
You're welcome!

**Comment by mario8x** [comment]
@kirovboris , 

The latest version doesn't work with IE 11.
There are some react components will return null: `Alert, AlertView, Brand, LoginForm`.

I tried to run my test script above with IE 11, then it would return the result as below:

```
 Running tests in:
 - IE 11.0.0 / Windows 10 0.0.0

 Todo App test
AlertView null
Alert null
FormundefinedonSubmit --noValidate --component --layout --
SigninViewundefinedbrand --from --logo --user --userCanAccessKeystone --
Brandnull
LoginFormnull
FormFieldundefinedlabel --htmlFor --
Buttonundefineddisabled --color --type --aphroditeStyles --variant --
 √ [demo]: login failed
```
