### ISSUE TITLE
Find components inside Portals

### ISSUE THREAD

**Issue by dimaip** [DevExpress/testcafe-react-selectors#33]
We at the Neos CMS render some components [inside an iframe portal](https://github.com/neos/neos-ui/blob/master/packages/react-ui-components/src/Frame/frame.js#L32) (with unstable_renderSubtreeIntoContainer).

Of course, current react selectors are not able to find it as it's detached from the main rendering tree.

What would be the way to go to test such stuff? Custom helper to find the dom node inside an iframe and get react instance of it via `__reactInternalSomething...` property?
Any chance to support such usecase in this package, as it might be a pretty common usecase to test portals (e.g. modals).

**Comment by kirovboris** [comment]
TestCafe has the [switchToIframe](https://devexpress.github.io/testcafe/documentation/test-api/working-with-iframes.html#switching-to-an-iframe) action for such purposes.

**Comment by dimaip** [comment]
I tried, but it didn't help. I mean it doesn't even work when I render with `unstable_renderSubtreeIntoContainer` in the same page, e.g. for modals.

**Comment by kirovboris** [comment]
Please, try to get the appropriate DOM elements with regular css selector instead of react selectors.

**Comment by dimaip** [comment]
I can't do that because I use CSS modules. But even if I could, I'd still need to get the react instance to make assertions on the props...

**Comment by kirovboris** [comment]
Make sure that the element you are trying to find exists on the page. 
To stop the script before selector execution, you can use the following expression during the test (developer tools should be opened):
```js
import { ClientFunction } from 'testcafe';
 
await ClientFunction(() => {
    debugger;
})();
 
//Getting selector here... 
 
```
Also, if it doesn't help, could you provide a link to a demo page or your site where this issue is reproduced?

**Comment by dimaip** [comment]
Sorry for the delayed response, I was on vacation.
The element does exist on the page.
Here is the code: https://github.com/neos/neos-ui/blob/master/packages/react-ui-components/src/Frame/frame.js#L32

**Comment by dimaip** [comment]
related: https://github.com/airbnb/enzyme/issues/252

**Comment by dimaip** [comment]
So currently there's only one way around it seems: popular portal packages like react-portal store the dom node into which the subtree has been rendered under `componentInstance.portal`: https://github.com/tajo/react-portal/blob/master/src/portal.js#L146

So to test it we'd need two things:
1. `.getReact()` method when called without arguments should return the full react component instance, and not only props and state.
2. `ReactSelector` should accept an optional argument for rootElement.

So it could be used like this:
```
const portalNode = ReactSelector('MyModal').getReact().portal;
const titleInsidePortal = ReactSelector('Title', portalNode);
```
Wdyt? If you agree on the API I could try to implement it.

Without this any projects that uses portals/modals would be quite hard to test, our project uses modals for most of navigation...

**Comment by kirovboris** [comment]
ReactSelector looks through all the DOM elements with the `data-reactroot` attribute.
As far as I understand, `unstable_renderSubtreeIntoContainer` adds the `data-reactroot` attribute as well. But it seems we can't get a child component for a portal container.
This occurs because the proper component attaches to `CommentNode` instead of the DOM node with the `data-reactroot` attribute.

So
```js
ReactSelector('Portal')
//and
ReactSelector('NestedPortalComponent')
```
will be work, but
```js
ReactSelector('Portal NestedPortalComponent')
```
won't.

Could you please check it with `react-dev-tools`? Are you able to see a class name of the portal?
I ran several tests and can get child components without using the portal class.

Since TestCafe serializes client objects, we can't just store a component instance in the test process (nodejs process on the server side).
So a fix implies that we should find some connection between the component and the DOM node with the `data-reactroot` attribute.
I need some time to investigate this case thoroughly. At first sight, the component instance stores the `container` link to the DOM element, which contains child components, so we can use it.

**Comment by dimaip** [comment]
You are right, each portal target has `data-reactroot`, didn't know it!
But, I can not find any child component still:
```
    const AddNodeButton = ReactSelector('AddNode Button');
    await t.click(AddNodeButton);
    const NodeTypeGroupPanel = ReactSelector('NodeTypeGroupPanel');
    await t.expect(NodeTypeItem.exists).ok();
```
results in `AssertionError: expected false to be truthy`
![image](https://user-images.githubusercontent.com/837032/29569043-ffbf2aa0-875a-11e7-9a9c-9fe0b654a5fc.png)

**Comment by dimaip** [comment]
Some more input. I try to step through the code, and I think the problem comes from this: `getRootComponent(rootEl)` returns an instance of Portal component, and not of its contents.
Then if you step down the chain of `_renderedComponent` you'll eventually get to `ReactDOMEmptyComponent` which corresponds to the comment node and which doesn't have and `_renderedChildren`.
The only way to drill down from it is to first jump to `_hostParent` and then go to its `_renderedChildren`:
`reactComponent._renderedComponent._renderedComponent._hostParent._renderedChildren['.2']._renderedComponent._renderedComponent._instance`

![image](https://user-images.githubusercontent.com/837032/29573758-74be9ce8-8768-11e7-8364-87a3993e6b3f.png)

**Comment by dimaip** [comment]
@kirovboris so, any ideas about this, or should I just use id's for now inside portals?

**Comment by kirovboris** [comment]
I'm working on fix this issue.
If I understood it correctly, `NodeTypeGroupPanel` is a `PureComponent`. I need check out the `ReactSelector` for such cases.

**Comment by dimaip** [comment]
@kirovboris yes it is https://github.com/neos/neos-ui/blob/master/packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeGroupPanel.js#L20

**Comment by kirovboris** [comment]
I've just published `testcafe-react-selectors@0.0.8-alpha2`.
Could you please check this out?

**Comment by dimaip** [comment]
@kirovboris thanks!
Quickly tested, doesn't seem to work so far.
WIll try to drill into the issue deeper tomorrow.

**Comment by kirovboris** [comment]
Could you please try `testcafe-react-selectors@0.0.8-alpha3`?

**Comment by dimaip** [comment]
No luck:

![image](https://user-images.githubusercontent.com/837032/29815292-cd2d5cb6-8cb8-11e7-80f9-1cd06b319e22.png)

**Comment by dimaip** [comment]
Perhaps it's important to note: the modal is empty by default, I open it during the test. When the modal is closed, its contents is null.

**Comment by kirovboris** [comment]
Thank you! I'll install `neos` with the react UI and test it. I'll let you know in case I have questions.

**Comment by dimaip** [comment]
@kirovboris oh, it's very kind of you!
In this case check out this PR: https://github.com/neos/neos-ui/pull/839

My current test that fails:
```js
import {Selector, Role} from 'testcafe';
import ReactSelector from 'testcafe-react-selectors';

const adminUrl = 'http://127.0.0.1:8081/neos!';

const adminUser = Role(adminUrl, async t => {
    await t
        .typeText('#username', 'admin')
        .typeText('#password', 'password')
        .click('button.neos-login-btn');
}, {preserveUrl: true});

fixture `ContentCanvas`
    .beforeEach(async t => {
        await t.useRole(adminUser);
    });

test.only('Can open node creation dialog', async t => {
    const AddNodeButton = ReactSelector('AddNode Button');
    const SelectNodeTypeModal = ReactSelector('SelectNodeType');
    const NodeType = ReactSelector('InsertModeSelector');
    await t.expect(SelectNodeTypeModal.exists).ok();
    await t.expect(SelectNodeTypeModal.getReact(({props}) => props.isOpen)).eql(false);
    await t.click(AddNodeButton);
    await t.expect(NodeType.exists).ok();
    await t.expect(SelectNodeTypeModal.getReact(({props}) => props.isOpen)).eql(true);
});
```

**Comment by dimaip** [comment]
Also ping me if you need an Docker container or some other help getting it installed.

**Comment by kirovboris** [comment]
I've just published `testcafe-react-selectors@0.0.8-alpha4`.
I also wish to note that the selector `ReactSelector('AddNode Button')` looks for `Button` component inside of `AddNode` component. If you want to find the tag `<button>` use
```js
ReactSelector('AddNode').find('button')
//or
ReactSelector('AddNode button') 
```
The first option is equivalent of  `Selector('.component_class button')`, 
the second - `Selector('.component_class > button')`.

**Comment by dimaip** [comment]
Hey @kirovboris!
In this case I wanted to click on the `Button` component, not to couple the test to the tag name of the button.

I'm testing `alpha4` but it still doesn't seem to find the `InsertModeSelector`... Maybe I'm doing smth wrong? Did you manage to test it with Neos?

**Comment by kirovboris** [comment]
> Did you manage to test it with Neos?

Yes, this test passed in my case - https://github.com/DevExpress/testcafe-react-selectors/issues/33#issuecomment-325622947
I used `dev-master` version of `neos-ui`. Did something change in your application?

**Comment by dimaip** [comment]
@kirovboris this is super strange... To be absolutely sure, with what command do you run the test and in what browser?

**Comment by dimaip** [comment]
What I did:
```
git reset --hard upstream/master
yarn
yarn add testcafe testcafe-react-selectors@0.0.8-alpha3
yarn build:ui
vi test.js <-- past contents of the test here from the comment above, literally
yarn run testcafe chrome test.js
```
At this point I see the test fail.
Also I have this in my settings:
```
  Neos:
    Ui:
      frontendDevelopmentMode: true
```

Maybe we could chat somewhere to speed up debugging? Twitter DM? Telegram?

**Comment by kirovboris** [comment]
Check out your twitter DM please.
